const app = {
  name: 'Orago',
  description:
    'Orago is organic grocery store. We deliver fresh and organic groceries to your doorstep.',
  keywords: [
    'orago',
    'organic',
    'grocery',
    'store',
    'fresh',
    'food',
    'vegetables',
    'fruits',
    'meat',
    'fish',
    'dairy',
    'bakery',
    'beverages',
    'snacks',
    'home',
    'delivery',
    'doorstep',
    'online',
    'shopping',
    'ecommerce',
    'makanan',
    'sayur',
    'buah',
    'daging',
    'ikan',
    'susu',
    'roti',
    'minuman',
    'makanan ringan',
    'rumah',
    'indonesia',
    'jakarta',
    'food store terdekat',
    'belanja online',
  ],
};

export default app;
